version: "3.8"

services:
  backend:
    build: ./messaging/.
    ports: 
      - "8081:8081"
  
  frontend:
    build: ./frontend-vue/.
    command: npm run serve 
    ports: 
      - "8090:8090"
  
  nginx:
    build: ./nginx/.
    ports:
      - "5000:80"
    depends_on:
    - backend
